"""recreate users with uuid pk

Revision ID: 16d2e74ddb02
Revises: 6db7b7f0e2c2
Create Date: 2026-07-09 16:36:31.030364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16d2e74ddb02'
down_revision: Union[str, Sequence[str], None] = '6db7b7f0e2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
