"""Updated User Role

Revision ID: 32f5bf5e9f71
Revises: 751ae5efe0a8
Create Date: 2026-07-09 19:46:31.010909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f5bf5e9f71'
down_revision: Union[str, Sequence[str], None] = '751ae5efe0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("ALTER TYPE userrole RENAME TO role")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE role RENAME TO userrole")

    # ### end Alembic commands ###
