"""Created AuthorProfile table + use the standard timezone for updated_at and created_at columns

Revision ID: 751ae5efe0a8
Revises: 16d2e74ddb02
Create Date: 2026-07-09 16:52:56.768554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '751ae5efe0a8'
down_revision: Union[str, Sequence[str], None] = '16d2e74ddb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pen_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_handle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_profile_pen_name'), 'author_profile', ['pen_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_profile_pen_name'), table_name='author_profile')
    op.drop_table('author_profile')
    # ### end Alembic commands ###
