"""Updated these users table columns 'is_disabled' and 'email_verified_at'

Revision ID: b4e5250e931c
Revises: a812f9cc3d63
Create Date: 2026-07-06 19:47:48.381899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4e5250e931c'
down_revision: Union[str, Sequence[str], None] = 'a812f9cc3d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'is_disabled')
    # ### end Alembic commands ###
